fix: handle errors during package addition to aptly repo and clean up on failure

diff --git a/.github/workflows/build-deb.yml b/.github/workflows/build-deb.yml
--- a/.github/workflows/build-deb.yml
+++ b/.github/workflows/build-deb.yml
@@ -179,6 +179,13 @@ jobs:
               do
                 echo "Adding ${pkg}"
                 ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'aptly repo add -remove-files '"${APTLY_REPO}-bookworm"' /mnt/pub_zynthbox_io_volume/temp/${pkg}'
+                status=$?
+                if [ $status -ne 0 ]; then
+                  echo "aptly repo add failed for ${pkg}, removing lock file and exiting."
+                    ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'if [[ -f /tmp/publish-aptly-zynthbox.lock ]]; then rm /tmp/publish-aptly-zynthbox.lock; fi'
+                    ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'rm -f /mnt/pub_zynthbox_io_volume/temp/$(basename ${pkg})'
+                  exit $status
+                fi
             done
             echo "Publishing repository"
             ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aptly@repo.zynthbox.io 'aptly publish update bookworm '"${APTLY_REPO}-bookworm"
